name: efood_multivendor_driver
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore:
  get: ^4.6.1
  shared_preferences: ^2.0.6
  cached_network_image:
  connectivity: ^3.0.6
  firebase_core: ^1.2.1
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.2.0
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  pin_code_fields: ^7.2.0
  http: ^0.13.3
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  url_launcher: ^6.0.9
  vibration: ^1.7.6
  image_picker: ^0.8.0+4
  disable_battery_optimization: ^1.1.0+1
  phone_number:
  #  ^1.0.0
  country_picker: ^2.0.18
  country_code_picker: ^2.0.2
  location: ^4.3.0
  audioplayers: ^0.20.1
  flutter_widget_from_html_core: ^0.8.4
  fwfh_text_style: ^2.7.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon.png"
  remove_alpha_ios: true
  
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900